#!/usr/bin/env bash
# shared/instructions/ の原本から claude/CLAUDE.md と codex/AGENTS.md を生成する
set -euo pipefail
cd "$(dirname "$0")"

generate() {
  local out="$1"
  {
    echo "<!-- GENERATED by imk-harness/build.sh -->"
    echo
    for f in shared/instructions/*.md; do
      cat "$f"
      echo
    done
  } > "$out"
  echo "generated: $out"
}

mkdir -p claude codex
generate claude/CLAUDE.md
# 現状は内容共通。Claude/Codex で差分が必要になったらここで分岐する
generate codex/AGENTS.md
